# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_auto_20210711_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commenting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clone.Profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clone.Image')),
            ],
        ),
    ]
